server:
  port: 8080
  servlet:
    context-path: /gaia-f

spring:
  application:
    name: gaia-f-core
    
experiment:
  cycleCount: 1500
  repoCapacity: 200

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always